### ISSUE TITLE
Primeiro EPIC (aka Roadmap)

### ISSUE THREAD

**Issue by PedroHLC** [bigarcia/ByteSurfer#1]
Fase Zero:
* [X] Definir o jogo
* [X] Definir a jogabilidade e interface
* [X] Relatório 1

Fase Alpha:
* [X] Ajustes pós apresentação
* [X] Definir a seção de dados (pseudo linguagem)
* [X] Definir o loop principal (pseudo linguagem)
* [X] Definir telas secúndarias
  * Titulo
  * Instruções
  * Pontuações
* [X] Diagrama de estados das telas
* [X] Descrição das rotinas
* [x] Relatório 2 #2

Fase Beta:
* [x] Ajustes pós apresentação
* [x] Implementar a seção de dados (masm) #3
* [x] Implementar o código (sem fases) #4
* [x] Testes #5 
* [x] Escolha das músicas #6
* [x] Criar as fases (Cada bloco, cada lane, com o tempo) #7
* [ ] Pós-produção #8
* [ ] Relatório 3 #9

Fase Final:
* [ ] Deploy

**Comment by PedroHLC** [comment]
Rotinas para futuras elaborações de código:
```
rotina Inicio:
	chama rotina Titulo

rotina Titulo:
	imprime tela de titulo
	repete:
		se pressiona F1 então
			chama rotina Instruções
		ou pressiona 1 então
			$nível = facíl
			chama rotina Jogo
		ou pressiona 2 então
			$nível = médio
			chama rotina Jogo
		ou pressiona 3 então
			$nível = difícil
			chama rotina Jogo
		ou pressiona ESC então
			fecha
		senão
			espera tempo minimo

rotina Instruções:
	imprime instruções
	repete:
		se pressiona ESC então
			chama rotina Titulo
		senão
			espera tempo minimo

rotina Pontuação:
	calcuma medalha
	imprime pontuação
	imprime medalha
	repete:
		se pressiona RETURN então
			chama rotina Titulo
		senão
			espera tempo minimo

rotina Jogo:
	inicializa variaveis
	chama subrotina Inicializa Pistas
	repete:
		chama subrotina Avança Passo
		se fim de jogo então
			chama Pontuação
		se pressiona ESC então
			chama Titulo
		se (não $bloqueado) e (colidiu com bloco) então
			se a pista estiver cheia então
				subrotina Tratar Combinações
				se a pista estiver cheia então
					chamar subrotina Bloquear
			chamar subrotina Adicionar Bloco
		se jogador está a 3 steps sem obter blocos então
			chamar subrotina Tratar Combinações
		chamar subrotina Imprimir Jogo
		se pressiona SETA_PARA_CIMA então
			se $posição_jogador < qtd_pistas então
				incrementa $posição_jogador
		ou pressiona SETA_PARA_BAIXO então
			se $posição_jogador > 1 então
				decrementa $posição_jogador
		espera passo

subrotina Inicializa Pistas:
	para cada pista:
		insere cabeça vazia
	distribui 6 passos

subrotina Avança Passo:
	decrementa bloqueado
	para cada pista:
		remove cabeça
	distribui 1 passo

subrotina Tratar Combinações:
	procura combinações
	se há combinações então
		contabenizar pontos das combinações
		remover blocos combinados

subrotina Adicionar Bloco:
	adiciona bloco ao iventario

subrotina Bloquear:
	$bloqueado = QTD_PASSOS_QUANDO_BLOQUEADO

subrotina Imprimir Jogo:
	para cada pista:
		imprimir iventário da pista
		imprimir jogador ou nada
		imprimir fila da pista
```
